#!/usr/bin/env python3
"""Generate the repetitive, kernel-checked permutation tuple equations.

Only declaration names come from Aeneas output. The expected slot operations
and output order below are independent specifications checked against that code.
"""
import argparse
import re
from verify import ROOT


def render():
    text = (ROOT / "lean/RustHammer/Rusthammer.lean").read_text()
    names = re.findall(r'\ndef\s+([\w.]+RusthammerPermutationLayout[\w]+)\s', text)
    items = re.findall(r'\ndef\s+([\w.]+RusthammerPermutationItems[\w]+)\s', text)
    if len(names) != 13 or len(items) != 13:
        raise RuntimeError(f"expected 13 tuple dictionaries, found {len(names)} layouts and {len(items)} item sets")
    # Charon emits all layout dictionaries before nonempty item dictionaries.
    # Both lists preserve the Rust macro's arity order.
    lines = ['-- Generated by tools/generate_permutation_tuple_proofs.py; edit the generator.', 'import RustHammer.PermutationProofs', '', 'open Aeneas Aeneas.Std Result WP', '',
             'namespace RustHammer.Permutation', 'open Code', '',
             '/- Storage equations for every public tuple arity. They establish independent',
             'slots, exact selected-child dispatch, and output assembly in declaration order.',
             'The mathematical search theorem uses these operations abstractly. -/', '']
    for n in range(1, 13):
        layout, item = names[n], items[n]
        ps = [f'P{i}' for i in range(n)]
        os = [f'O{i}' for i in range(n)]
        gs = [f'g{i}' for i in range(n)]
        iss = [f'e{i}' for i in range(n)]
        ss = [f's{i}' for i in range(n)]
        vals = [f'v{i}' for i in range(n)]
        tup = lambda xs: xs[0] if len(xs)==1 else '('+', '.join(xs)+')'
        prod = lambda xs: '('+' × '.join(xs)+')'
        state = tup(ss)
        args = ' '.join(gs)
        params = ' '.join(f'({g} : Grammar {p} {o})' for g,p,o in zip(gs, ps, os))
        slots = ' '.join(f'({s} : permutation.Slot {o})' for s,o in zip(ss, os))
        empty = tup([f'(⟨false, none⟩ : permutation.Slot {o})' for o in os])
        lines += [f'section Tuple{n}', f'variable {{'+ ' '.join(ps+os) +' : Type}',
            f'local notation "layout" => {layout}',
            f'local notation "entries" => {item}', '',
            f'theorem tuple{n}_initial {params} (parsers : {prod(ps)}) :',
            f'    (layout {args}).count parsers = ok {n}#usize ∧',
            f'    (layout {args}).empty parsers = ok {empty} := by',
            f'  simp [{layout}.count, {layout}.empty, permutation.empty_slot]', '',
            f'theorem tuple{n}_matched {params} (parsers : {prod(ps)}) {slots}',
            '    (index : Usize) :',
            f'    (layout {args}).matched parsers {state} index = ok (match index.val with']
        lines += [f'      | {i} => s{i}.matched' for i in range(n)]
        lines += ['      | _ => false) := by',f'  simp only [{layout}.matched]',
                  '  split <;> simp_all', '',
                  f'theorem tuple{n}_clear {params} (parsers : {prod(ps)}) {slots}',
                  '    (index : Usize) :',
                  f'    (layout {args}).clear parsers {state} index = ok (match index.val with']
        for i in range(n):
            changed = ss.copy()
            changed[i] = '⟨false, none⟩'
            lines += [f'      | {i} => {tup(changed)}']
        lines += [f'      | _ => {state}) := by',
                  f'  simp only [{layout}.clear]',
                  '  split <;> simp_all [permutation.empty_slot]', '',
                  f'def tuple{n}Finish {slots} : core.result.Result {prod(os)} ParseError :=']
        for i in range(n):
            lines += ['  '*(i+1)+f'match s{i}.value with', '  '*(i+1)+'| none => .Err .Mismatch', '  '*(i+1)+f'| some v{i} =>']
        lines += ['  '*(n+1)+f'.Ok {tup(vals)}', '',
                  f'theorem tuple{n}_finish {params} (parsers : {prod(ps)}) {slots} :',
                  f'    (layout {args}).finish parsers {state} = ok (tuple{n}Finish '+ ' '.join(ss)+') := by',
                  f'  simp only [{layout}.finish, permutation.slot_value, tuple{n}Finish]',
                  "  repeat' (split <;> simp_all)", '',
                  f'theorem tuple{n}_output_order {params} (parsers : {prod(ps)})',
                  '    '+ ' '.join(f'(v{i} : O{i}) (matched{i} : Bool)' for i in range(n)) +' :',
                  f'    (layout {args}).finish parsers '+tup([f'⟨matched{i}, some v{i}⟩' for i in range(n)])+ f' = ok (.Ok {tup(vals)}) := by',
                  f'  rw [tuple{n}_finish]; rfl', '',
                  f'theorem tuple{n}_dispatch {{B : Type}}',
                  '    '+ ' '.join(f'({e} : permutation.ItemEval {p} B {o})' for e,p,o in zip(iss, ps, os)),
                  '    '+ ' '.join(f'(p{i} : P{i})' for i in range(n)) +' '+ slots,
                  '    (backend : B) (input : Slice U8) (cursor : Cursor) (context : ParseContext)',
                  '    '+ ' '.join(f'(r{i} : (permutation.Attempt × permutation.Slot O{i}) × B)' for i in range(n))]
        lines += [f'    (h{i} : e{i}.eval_slot p{i} backend input cursor context = ok r{i})' for i in range(n)]
        lines += ['    (index : Usize) :',f'    (entries '+ ' '.join(iss)+f').attempt '+tup([f'p{i}' for i in range(n)])+f' {state} index backend input cursor context',
                  '      = ok (match index.val with']
        for i in range(n):
            changed = ss.copy()
            changed[i] = f'r{i}.1.2'
            lines += [f'        | {i} => ((r{i}.1.1, {tup(changed)}), r{i}.2)']
        lines += [f'        | _ => ((.Error .Mismatch, {state}), backend)) := by',
                  *(f'  rcases r{i} with ⟨⟨a{i}, slot{i}⟩, b{i}⟩' for i in range(n)),
                  f'  simp only [{item}.attempt]',
                  '  split <;> simp_all', '',f'end Tuple{n}', '']
    lines += ['end RustHammer.Permutation','']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="reject stale proof source")
    args = parser.parse_args()
    destination = ROOT / "lean/RustHammer/PermutationTupleProofs.lean"
    expected = render()
    if args.check:
        if destination.read_text() != expected:
            raise SystemExit("Tuple proof source is stale; run tools/generate_permutation_tuple_proofs.py")
        print("Permutation tuple proof source is current (arities 1–12).")
    else:
        destination.write_text(expected)


if __name__ == "__main__":
    main()
