-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rusthammer]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace RustHammer.Code

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 811:0-811:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- [core::option::{impl core::clone::Clone for core::option::Option<T>}::clone]:
    Source: '/rustc/library/core/src/option.rs', lines 2278:4-2278:27
    Name pattern: [core::option::{core::clone::Clone<core::option::Option<@T>>}::clone]
    Visibility: public -/
@[rust_fun
  "core::option::{core::clone::Clone<core::option::Option<@T>>}::clone"]
def core.option.Option.Insts.CoreCloneClone.clone
  {T : Type} (cloneCloneInst : core.clone.Clone T) (self : Option T) :
  Result (Option T)
  := do
  match self with
  | none => ok none
  | some x => let t ← cloneCloneInst.clone x
              ok (some t)

/-- [rusthammer::Cursor]
    Source: 'src/lib.rs', lines 47:0-50:1
    Visibility: public -/
structure Cursor where
  byte : Std.Usize
  bit : Std.U8

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Cursor}::clone]:
    Source: 'src/lib.rs', lines 46:9-46:14
    Visibility: public -/
def Cursor.Insts.CoreCloneClone.clone (self : Cursor) : Result Cursor := do
  ok self

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Cursor}]
    Source: 'src/lib.rs', lines 46:9-46:14 -/
@[reducible]
def Cursor.Insts.CoreCloneClone : core.clone.Clone Cursor := {
  clone := Cursor.Insts.CoreCloneClone.clone
}

/-- [rusthammer::ConfigError]
    Source: 'src/lib.rs', lines 60:0-67:1
    Visibility: public -/
@[discriminant isize]
inductive ConfigError where
| InvalidWidth : ConfigError
| InvalidLiteral : ConfigError
| InvalidBounds : ConfigError

/-- [rusthammer::{impl core::clone::Clone for rusthammer::ConfigError}::clone]:
    Source: 'src/lib.rs', lines 59:9-59:14
    Visibility: public -/
def ConfigError.Insts.CoreCloneClone.clone
  (self : ConfigError) : Result ConfigError := do
  ok self

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::ConfigError}]
    Source: 'src/lib.rs', lines 59:9-59:14 -/
@[reducible]
def ConfigError.Insts.CoreCloneClone : core.clone.Clone ConfigError := {
  clone := ConfigError.Insts.CoreCloneClone.clone
}

/-- [rusthammer::ParseError]
    Source: 'src/lib.rs', lines 71:0-81:1
    Visibility: public -/
@[discriminant isize]
inductive ParseError where
| InvalidCursor : ParseError
| UnexpectedEnd : ParseError
| Unaligned : ParseError
| Mismatch : ParseError
| TrailingInput : ParseError
| NonProgress : ParseError
| CountOverflow : ParseError

/-- [rusthammer::{impl core::clone::Clone for rusthammer::ParseError}::clone]:
    Source: 'src/lib.rs', lines 70:9-70:14
    Visibility: public -/
def ParseError.Insts.CoreCloneClone.clone
  (self : ParseError) : Result ParseError := do
  ok self

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::ParseError}]
    Source: 'src/lib.rs', lines 70:9-70:14 -/
@[reducible]
def ParseError.Insts.CoreCloneClone : core.clone.Clone ParseError := {
  clone := ParseError.Insts.CoreCloneClone.clone
}

/-- [rusthammer::{rusthammer::ParseError}::is_recoverable]:
    Source: 'src/lib.rs', lines 87:4-94:5
    Visibility: public -/
def ParseError.is_recoverable (self : ParseError) : Result Bool := do
  match self with
  | ParseError.InvalidCursor => ok false
  | ParseError.UnexpectedEnd => ok true
  | ParseError.Unaligned => ok false
  | ParseError.Mismatch => ok true
  | ParseError.TrailingInput => ok true
  | ParseError.NonProgress => ok false
  | ParseError.CountOverflow => ok false

/-- [rusthammer::InputStatus]
    Source: 'src/lib.rs', lines 99:0-104:1
    Visibility: public -/
@[discriminant isize]
inductive InputStatus where
| Partial : InputStatus
| Final : InputStatus

/-- [rusthammer::{impl core::clone::Clone for rusthammer::InputStatus}::clone]:
    Source: 'src/lib.rs', lines 98:9-98:14
    Visibility: public -/
def InputStatus.Insts.CoreCloneClone.clone
  (self : InputStatus) : Result InputStatus := do
  ok self

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::InputStatus}]
    Source: 'src/lib.rs', lines 98:9-98:14 -/
@[reducible]
def InputStatus.Insts.CoreCloneClone : core.clone.Clone InputStatus := {
  clone := InputStatus.Insts.CoreCloneClone.clone
}

/-- [rusthammer::ParseOutcome]
    Source: 'src/lib.rs', lines 110:0-114:1
    Visibility: public -/
@[discriminant isize]
inductive ParseOutcome (T : Type) where
| Success : Cursor → T → ParseOutcome T
| Error : ParseError → ParseOutcome T
| NeedMore : ParseOutcome T

/-- [rusthammer::{rusthammer::InputStatus}::classify]:
    Source: 'src/lib.rs', lines 119:4-135:5 -/
def InputStatus.classify
  {T : Type} (self : InputStatus)
  (result : core.result.Result (Cursor × T) ParseError) :
  Result (ParseOutcome T)
  := do
  match result with
  | core.result.Result.Ok parsed =>
    let (next, value) := parsed
    ok (ParseOutcome.Success next value)
  | core.result.Result.Err pe =>
    match pe with
    | ParseError.InvalidCursor =>
      ok (ParseOutcome.Error ParseError.InvalidCursor)
    | ParseError.UnexpectedEnd =>
      match self with
      | InputStatus.Partial => ok ParseOutcome.NeedMore
      | InputStatus.Final => ok (ParseOutcome.Error ParseError.UnexpectedEnd)
    | ParseError.Unaligned => ok (ParseOutcome.Error ParseError.Unaligned)
    | ParseError.Mismatch => ok (ParseOutcome.Error ParseError.Mismatch)
    | ParseError.TrailingInput =>
      ok (ParseOutcome.Error ParseError.TrailingInput)
    | ParseError.NonProgress => ok (ParseOutcome.Error ParseError.NonProgress)
    | ParseError.CountOverflow =>
      ok (ParseOutcome.Error ParseError.CountOverflow)

/-- [rusthammer::{rusthammer::ParseOutcome<T>}::into_complete]:
    Source: 'src/lib.rs', lines 139:4-147:5 -/
def ParseOutcome.into_complete
  {T : Type} (self : ParseOutcome T) :
  Result (core.result.Result (Cursor × T) ParseError)
  := do
  match self with
  | ParseOutcome.Success next value => ok (core.result.Result.Ok (next, value))
  | ParseOutcome.Error error => ok (core.result.Result.Err error)
  | ParseOutcome.NeedMore =>
    ok (core.result.Result.Err ParseError.UnexpectedEnd)

/-- Trait declaration: [rusthammer::Parser]
    Source: 'src/lib.rs', lines 154:0-183:1
    Visibility: public -/
structure Parser (Self : Type) (Self_Output : Type) where
  parse_with : Self → Slice Std.U8 → Cursor → InputStatus → Result
    (ParseOutcome Self_Output)
  parse : Self → Slice Std.U8 → Cursor → Result (core.result.Result
    (Cursor × Self_Output) ParseError)

/-- [rusthammer::Parser::parse]:
    Source: 'src/lib.rs', lines 175:4-182:5
    Visibility: public -/
@[trait_default]
def Parser.parse.default
  {Self : Type} {Clause0_Output : Type} (ParserInst : Parser Self
  Clause0_Output) (self : Self) (input : Slice Std.U8) (cursor : Cursor) :
  Result (core.result.Result (Cursor × Clause0_Output) ParseError)
  := do
  let po ← ParserInst.parse_with self input cursor InputStatus.Final
  ParseOutcome.into_complete po

/-- [rusthammer::{impl rusthammer::Parser<'input, Clause0_Output> for &'_1 P}::parse]:
    Source: 'src/lib.rs', lines 199:4-205:5
    Visibility: public -/
def Shared0P.Insts.RusthammerParser.parse
  {P : Type} {Clause0_Output : Type} (ParserInst : Parser P Clause0_Output)
  (self : P) (input : Slice Std.U8) (cursor : Cursor) :
  Result (core.result.Result (Cursor × Clause0_Output) ParseError)
  := do
  ParserInst.parse self input cursor

/-- [rusthammer::{impl rusthammer::Parser<'input, Clause0_Output> for &'_1 P}::parse_with]:
    Source: 'src/lib.rs', lines 190:4-197:5
    Visibility: public -/
def Shared0P.Insts.RusthammerParser.parse_with
  {P : Type} {Clause0_Output : Type} (ParserInst : Parser P Clause0_Output)
  (self : P) (input : Slice Std.U8) (cursor : Cursor) (status : InputStatus) :
  Result (ParseOutcome Clause0_Output)
  := do
  ParserInst.parse_with self input cursor status

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, Clause0_Output> for &'_1 P}]
    Source: 'src/lib.rs', lines 187:0-206:1 -/
@[reducible]
def Shared0P.Insts.RusthammerParser {P : Type} {Clause0_Output : Type}
  (ParserInst : Parser P Clause0_Output) : Parser P Clause0_Output := {
  parse_with := Shared0P.Insts.RusthammerParser.parse_with ParserInst
  parse := Shared0P.Insts.RusthammerParser.parse ParserInst
}

/-- [rusthammer::read_bit]:
    Source: 'src/lib.rs', lines 210:0-235:1
    Visibility: public -/
def read_bit
  (input : Slice Std.U8) (cursor : Cursor) :
  Result (core.result.Result (Cursor × Bool) ParseError)
  := do
  if cursor.bit >= 8#u8
  then ok (core.result.Result.Err ParseError.InvalidCursor)
  else
    let i := Slice.len input
    if cursor.byte >= i
    then
      let i1 := Slice.len input
      if cursor.byte = i1
      then
        if cursor.bit = 0#u8
        then ok (core.result.Result.Err ParseError.UnexpectedEnd)
        else ok (core.result.Result.Err ParseError.InvalidCursor)
      else ok (core.result.Result.Err ParseError.InvalidCursor)
    else
      let i1 ← Slice.index_usize input cursor.byte
      let i2 ← 7#u8 - cursor.bit
      let i3 ← i1 >>> i2
      let i4 ← lift (i3 &&& 1#u8)
      if cursor.bit = 7#u8
      then
        let i5 ← cursor.byte + 1#usize
        ok (core.result.Result.Ok ({ byte := i5, bit := 0#u8 }, i4 != 0#u8))
      else
        let i5 ← cursor.bit + 1#u8
        ok (core.result.Result.Ok ({ cursor with bit := i5 }, i4 != 0#u8))

/-- [rusthammer::Bit]
    Source: 'src/lib.rs', lines 238:0-238:15
    Visibility: public -/
@[reducible]
def Bit := Unit

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Bit}::clone]:
    Source: 'src/lib.rs', lines 237:9-237:14
    Visibility: public -/
def Bit.Insts.CoreCloneClone.clone (self : Bit) : Result Bit := do
  ok self

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Bit}]
    Source: 'src/lib.rs', lines 237:9-237:14 -/
@[reducible]
def Bit.Insts.CoreCloneClone : core.clone.Clone Bit := {
  clone := Bit.Insts.CoreCloneClone.clone
}

/-- [rusthammer::{impl rusthammer::Parser<'input, bool> for rusthammer::Bit}::parse_with]:
    Source: 'src/lib.rs', lines 243:4-250:5
    Visibility: public -/
def Bit.Insts.RusthammerParserInputBool.parse_with
  (self : Bit) (input : Slice Std.U8) (cursor : Cursor) (status : InputStatus)
  :
  Result (ParseOutcome Bool)
  := do
  let r ← read_bit input cursor
  InputStatus.classify status r

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, bool> for rusthammer::Bit}]
    Source: 'src/lib.rs', lines 240:0-251:1 -/
@[reducible]
impl_def Bit.Insts.RusthammerParserInputBool : Parser Bit Bool := {
  parse_with := Bit.Insts.RusthammerParserInputBool.parse_with
  parse := Parser.parse.default Bit.Insts.RusthammerParserInputBool
}

/-- [rusthammer::Bits]
    Source: 'src/lib.rs', lines 264:0-266:1
    Visibility: public -/
structure Bits where
  width : Std.U8

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Bits}::clone]:
    Source: 'src/lib.rs', lines 263:9-263:14
    Visibility: public -/
def Bits.Insts.CoreCloneClone.clone (self : Bits) : Result Bits := do
  ok self

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Bits}]
    Source: 'src/lib.rs', lines 263:9-263:14 -/
@[reducible]
def Bits.Insts.CoreCloneClone : core.clone.Clone Bits := {
  clone := Bits.Insts.CoreCloneClone.clone
}

/-- [rusthammer::{rusthammer::Bits}::new]:
    Source: 'src/lib.rs', lines 270:4-276:5
    Visibility: public -/
def Bits.new
  (width : Std.U8) : Result (core.result.Result Bits ConfigError) := do
  if width > 64#u8
  then ok (core.result.Result.Err ConfigError.InvalidWidth)
  else ok (core.result.Result.Ok { width })

/-- [rusthammer::{rusthammer::Bits}::width]:
    Source: 'src/lib.rs', lines 279:4-281:5
    Visibility: public -/
def Bits.impl.width (self : Bits) : Result Std.U8 := do
  ok self.width

/-- [rusthammer::read_bits]: loop body 0:
    Source: 'src/lib.rs', lines 308:4-320:1
    Visibility: public -/
@[rust_loop_body]
def read_bits_loop0.body
  (input : Slice Std.U8) (next : Cursor) (remaining : Std.U8) (value : Std.U64)
  :
  Result (ControlFlow (Cursor × Std.U8 × Std.U64) (core.result.Result (Cursor
    × Std.U64) ParseError))
  := do
  if remaining != 0#u8
  then
    let r ← read_bit input next
    match r with
    | core.result.Result.Ok p =>
      let (after, bit) := p
      let i ← value * 2#u64
      let i1 ← if bit
                 then ok 1#u64
                 else ok 0#u64
      let value1 ← i + i1
      let remaining1 ← remaining - 1#u8
      ok (cont (after, remaining1, value1))
    | core.result.Result.Err error => ok (done (core.result.Result.Err error))
  else ok (done (core.result.Result.Ok (next, value)))

/-- [rusthammer::read_bits]: loop 0:
    Source: 'src/lib.rs', lines 308:4-320:1
    Visibility: public -/
@[rust_loop]
def read_bits_loop0
  (input : Slice Std.U8) (next : Cursor) (remaining : Std.U8) (value : Std.U64)
  :
  Result (core.result.Result (Cursor × Std.U64) ParseError)
  := do
  loop
    (fun (next1, remaining1, value1) => read_bits_loop0.body input next1
      remaining1 value1)
    (next, remaining, value)

/-- [rusthammer::read_bits]: loop body 1:
    Source: 'src/lib.rs', lines 308:4-320:1
    Visibility: public -/
@[rust_loop_body]
def read_bits_loop1.body
  (input : Slice Std.U8) (next : Cursor) (remaining : Std.U8) (value : Std.U64)
  :
  Result (ControlFlow (Cursor × Std.U8 × Std.U64) (core.result.Result (Cursor
    × Std.U64) ParseError))
  := do
  if remaining != 0#u8
  then
    let r ← read_bit input next
    match r with
    | core.result.Result.Ok p =>
      let (after, bit) := p
      let i ← value * 2#u64
      let i1 ← if bit
                 then ok 1#u64
                 else ok 0#u64
      let value1 ← i + i1
      let remaining1 ← remaining - 1#u8
      ok (cont (after, remaining1, value1))
    | core.result.Result.Err error => ok (done (core.result.Result.Err error))
  else ok (done (core.result.Result.Ok (next, value)))

/-- [rusthammer::read_bits]: loop 1:
    Source: 'src/lib.rs', lines 308:4-320:1
    Visibility: public -/
@[rust_loop]
def read_bits_loop1
  (input : Slice Std.U8) (next : Cursor) (remaining : Std.U8) (value : Std.U64)
  :
  Result (core.result.Result (Cursor × Std.U64) ParseError)
  := do
  loop
    (fun (next1, remaining1, value1) => read_bits_loop1.body input next1
      remaining1 value1)
    (next, remaining, value)

/-- [rusthammer::read_bits]:
    Source: 'src/lib.rs', lines 298:0-320:1
    Visibility: public -/
def read_bits
  (input : Slice Std.U8) (cursor : Cursor) (parser : Bits) :
  Result (core.result.Result (Cursor × Std.U64) ParseError)
  := do
  if cursor.bit >= 8#u8
  then ok (core.result.Result.Err ParseError.InvalidCursor)
  else
    let i := Slice.len input
    if cursor.byte > i
    then ok (core.result.Result.Err ParseError.InvalidCursor)
    else
      let i1 := Slice.len input
      if cursor.byte = i1
      then
        if cursor.bit != 0#u8
        then ok (core.result.Result.Err ParseError.InvalidCursor)
        else read_bits_loop0 input cursor parser.width 0#u64
      else read_bits_loop1 input cursor parser.width 0#u64

/-- [rusthammer::{impl rusthammer::Parser<'input, u64> for rusthammer::Bits}::parse_with]:
    Source: 'src/lib.rs', lines 287:4-294:5
    Visibility: public -/
def Bits.Insts.RusthammerParserInputU64.parse_with
  (self : Bits) (input : Slice Std.U8) (cursor : Cursor) (status : InputStatus)
  :
  Result (ParseOutcome Std.U64)
  := do
  let r ← read_bits input cursor self
  InputStatus.classify status r

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, u64> for rusthammer::Bits}]
    Source: 'src/lib.rs', lines 284:0-295:1 -/
@[reducible]
impl_def Bits.Insts.RusthammerParserInputU64 : Parser Bits Std.U64 := {
  parse_with := Bits.Insts.RusthammerParserInputU64.parse_with
  parse := Parser.parse.default Bits.Insts.RusthammerParserInputU64
}

/-- [rusthammer::Literal]
    Source: 'src/lib.rs', lines 334:0-337:1
    Visibility: public -/
structure Literal where
  bits : Bits
  value : Std.U64

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Literal}::clone]:
    Source: 'src/lib.rs', lines 333:9-333:14
    Visibility: public -/
def Literal.Insts.CoreCloneClone.clone (self : Literal) : Result Literal := do
  ok self

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Literal}]
    Source: 'src/lib.rs', lines 333:9-333:14 -/
@[reducible]
def Literal.Insts.CoreCloneClone : core.clone.Clone Literal := {
  clone := Literal.Insts.CoreCloneClone.clone
}

/-- [rusthammer::{rusthammer::Literal}::new]:
    Source: 'src/lib.rs', lines 342:4-352:5
    Visibility: public -/
def Literal.new
  (width : Std.U8) (value : Std.U64) :
  Result (core.result.Result Literal ConfigError)
  := do
  let r ← Bits.new width
  match r with
  | core.result.Result.Ok bits =>
    if width < 64#u8
    then
      let i ← 1#u64 <<< width
      if value >= i
      then ok (core.result.Result.Err ConfigError.InvalidLiteral)
      else ok (core.result.Result.Ok { bits, value })
    else ok (core.result.Result.Ok { bits, value })
  | core.result.Result.Err error => ok (core.result.Result.Err error)

/-- [rusthammer::{rusthammer::Literal}::width]:
    Source: 'src/lib.rs', lines 355:4-357:5
    Visibility: public -/
def Literal.width (self : Literal) : Result Std.U8 := do
  Bits.impl.width self.bits

/-- [rusthammer::{rusthammer::Literal}::value]:
    Source: 'src/lib.rs', lines 360:4-362:5
    Visibility: public -/
def Literal.impl.value (self : Literal) : Result Std.U64 := do
  ok self.value

/-- [rusthammer::read_literal]:
    Source: 'src/lib.rs', lines 378:0-393:1 -/
def read_literal
  (input : Slice Std.U8) (cursor : Cursor) (parser : Literal) :
  Result (core.result.Result (Cursor × Std.U64) ParseError)
  := do
  let r ← read_bits input cursor parser.bits
  match r with
  | core.result.Result.Ok p =>
    let (_, value) := p
    if value = parser.value
    then ok r
    else ok (core.result.Result.Err ParseError.Mismatch)
  | core.result.Result.Err _ => ok r

/-- [rusthammer::{impl rusthammer::Parser<'input, u64> for rusthammer::Literal}::parse_with]:
    Source: 'src/lib.rs', lines 368:4-375:5
    Visibility: public -/
def Literal.Insts.RusthammerParserInputU64.parse_with
  (self : Literal) (input : Slice Std.U8) (cursor : Cursor)
  (status : InputStatus) :
  Result (ParseOutcome Std.U64)
  := do
  let r ← read_literal input cursor self
  InputStatus.classify status r

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, u64> for rusthammer::Literal}]
    Source: 'src/lib.rs', lines 365:0-376:1 -/
@[reducible]
impl_def Literal.Insts.RusthammerParserInputU64 : Parser Literal Std.U64 := {
  parse_with := Literal.Insts.RusthammerParserInputU64.parse_with
  parse := Parser.parse.default Literal.Insts.RusthammerParserInputU64
}

/-- [rusthammer::End]
    Source: 'src/lib.rs', lines 399:0-399:15
    Visibility: public -/
@[reducible]
def End := Unit

/-- [rusthammer::{impl core::clone::Clone for rusthammer::End}::clone]:
    Source: 'src/lib.rs', lines 398:9-398:14
    Visibility: public -/
def End.Insts.CoreCloneClone.clone (self : End) : Result End := do
  ok self

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::End}]
    Source: 'src/lib.rs', lines 398:9-398:14 -/
@[reducible]
def End.Insts.CoreCloneClone : core.clone.Clone End := {
  clone := End.Insts.CoreCloneClone.clone
}

/-- [rusthammer::{impl rusthammer::Parser<'input, ()> for rusthammer::End}::parse_with]:
    Source: 'src/lib.rs', lines 404:4-424:5
    Visibility: public -/
def End.Insts.RusthammerParserInputTuple.parse_with
  (self : End) (input : Slice Std.U8) (cursor : Cursor) (status : InputStatus)
  :
  Result (ParseOutcome Unit)
  := do
  if cursor.bit >= 8#u8
  then ok (ParseOutcome.Error ParseError.InvalidCursor)
  else
    let i := Slice.len input
    if cursor.byte > i
    then ok (ParseOutcome.Error ParseError.InvalidCursor)
    else
      let i1 := Slice.len input
      if cursor.byte = i1
      then
        if cursor.bit != 0#u8
        then ok (ParseOutcome.Error ParseError.InvalidCursor)
        else
          let i2 := Slice.len input
          if cursor.byte = i2
          then
            match status with
            | InputStatus.Partial => ok ParseOutcome.NeedMore
            | InputStatus.Final => ok (ParseOutcome.Success cursor ())
          else ok (ParseOutcome.Error ParseError.TrailingInput)
      else
        let i2 := Slice.len input
        if cursor.byte = i2
        then
          match status with
          | InputStatus.Partial => ok ParseOutcome.NeedMore
          | InputStatus.Final => ok (ParseOutcome.Success cursor ())
        else ok (ParseOutcome.Error ParseError.TrailingInput)

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, ()> for rusthammer::End}]
    Source: 'src/lib.rs', lines 401:0-425:1 -/
@[reducible]
impl_def End.Insts.RusthammerParserInputTuple : Parser End Unit := {
  parse_with := End.Insts.RusthammerParserInputTuple.parse_with
  parse := Parser.parse.default End.Insts.RusthammerParserInputTuple
}

/-- [rusthammer::Epsilon]
    Source: 'src/lib.rs', lines 431:0-431:19
    Visibility: public -/
@[reducible]
def Epsilon := Unit

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Epsilon}::clone]:
    Source: 'src/lib.rs', lines 430:9-430:14
    Visibility: public -/
def Epsilon.Insts.CoreCloneClone.clone (self : Epsilon) : Result Epsilon := do
  ok self

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Epsilon}]
    Source: 'src/lib.rs', lines 430:9-430:14 -/
@[reducible]
def Epsilon.Insts.CoreCloneClone : core.clone.Clone Epsilon := {
  clone := Epsilon.Insts.CoreCloneClone.clone
}

/-- [rusthammer::{impl rusthammer::Parser<'input, ()> for rusthammer::Epsilon}::parse_with]:
    Source: 'src/lib.rs', lines 436:4-438:5
    Visibility: public -/
def Epsilon.Insts.RusthammerParserInputTuple.parse_with
  (self : Epsilon) (s : Slice Std.U8) (cursor : Cursor) (is : InputStatus) :
  Result (ParseOutcome Unit)
  := do
  ok (ParseOutcome.Success cursor ())

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, ()> for rusthammer::Epsilon}]
    Source: 'src/lib.rs', lines 433:0-439:1 -/
@[reducible]
impl_def Epsilon.Insts.RusthammerParserInputTuple : Parser Epsilon Unit := {
  parse_with := Epsilon.Insts.RusthammerParserInputTuple.parse_with
  parse := Parser.parse.default Epsilon.Insts.RusthammerParserInputTuple
}

/-- [rusthammer::Fail]
    Source: 'src/lib.rs', lines 444:0-446:1
    Visibility: public -/
structure Fail (T : Type) where
  output : core.marker.PhantomData T

/-- [rusthammer::{rusthammer::Fail<T>}::new]:
    Source: 'src/lib.rs', lines 450:4-454:5
    Visibility: public -/
def Fail.new (T : Type) : Result (Fail T) := do
  ok { output := () }

/-- [rusthammer::{impl core::default::Default for rusthammer::Fail<T>}::default]:
    Source: 'src/lib.rs', lines 458:4-460:5
    Visibility: public -/
def Fail.Insts.CoreDefaultDefault.default (T : Type) : Result (Fail T) := do
  Fail.new T

/-- Trait implementation: [rusthammer::{impl core::default::Default for rusthammer::Fail<T>}]
    Source: 'src/lib.rs', lines 457:0-461:1 -/
@[reducible]
def Fail.Insts.CoreDefaultDefault (T : Type) : core.default.Default (Fail T)
  := {
  default := Fail.Insts.CoreDefaultDefault.default T
}

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Fail<T>}::clone]:
    Source: 'src/lib.rs', lines 466:4-468:5
    Visibility: public -/
def Fail.Insts.CoreCloneClone.clone
  {T : Type} (self : Fail T) : Result (Fail T) := do
  ok self

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Fail<T>}]
    Source: 'src/lib.rs', lines 465:0-469:1 -/
@[reducible]
def Fail.Insts.CoreCloneClone (T : Type) : core.clone.Clone (Fail T) := {
  clone := Fail.Insts.CoreCloneClone.clone
}

/-- [rusthammer::{impl rusthammer::Parser<'input, T> for rusthammer::Fail<T>}::parse_with]:
    Source: 'src/lib.rs', lines 474:4-476:5
    Visibility: public -/
def Fail.Insts.RusthammerParser.parse_with
  {T : Type} (self : Fail T) (s : Slice Std.U8) (c : Cursor) (is : InputStatus)
  :
  Result (ParseOutcome T)
  := do
  ok (ParseOutcome.Error ParseError.Mismatch)

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, T> for rusthammer::Fail<T>}]
    Source: 'src/lib.rs', lines 471:0-477:1 -/
@[reducible]
impl_def Fail.Insts.RusthammerParser (T : Type) : Parser (Fail T) T := {
  parse_with := Fail.Insts.RusthammerParser.parse_with
  parse := Parser.parse.default (Fail.Insts.RusthammerParser T)
}

/-- [rusthammer::Seq]
    Source: 'src/lib.rs', lines 482:0-485:1
    Visibility: public -/
structure Seq (P : Type) (Q : Type) where
  first : P
  second : Q

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Seq<P, Q>}::clone]:
    Source: 'src/lib.rs', lines 481:9-481:14
    Visibility: public -/
def Seq.Insts.CoreCloneClone.clone
  {P : Type} {Q : Type} (corecloneCloneInst : core.clone.Clone P)
  (corecloneCloneInst1 : core.clone.Clone Q) (self : Seq P Q) :
  Result (Seq P Q)
  := do
  let t ← corecloneCloneInst.clone self.first
  let t1 ← corecloneCloneInst1.clone self.second
  ok { first := t, second := t1 }

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Seq<P, Q>}]
    Source: 'src/lib.rs', lines 481:9-481:14 -/
@[reducible]
def Seq.Insts.CoreCloneClone {P : Type} {Q : Type} (corecloneCloneInst :
  core.clone.Clone P) (corecloneCloneInst1 : core.clone.Clone Q) :
  core.clone.Clone (Seq P Q) := {
  clone := Seq.Insts.CoreCloneClone.clone corecloneCloneInst
    corecloneCloneInst1
}

/-- [rusthammer::{impl rusthammer::Parser<'input, (Clause0_Output, Clause1_Output)> for rusthammer::Seq<P, Q>}::parse_with]:
    Source: 'src/lib.rs', lines 490:4-506:5
    Visibility: public -/
def Seq.Insts.RusthammerParserInputPair.parse_with
  {P : Type} {Q : Type} {Clause0_Output : Type} {Clause1_Output : Type}
  (ParserInst : Parser P Clause0_Output) (ParserInst1 : Parser Q
  Clause1_Output) (self : Seq P Q) (input : Slice Std.U8) (cursor : Cursor)
  (status : InputStatus) :
  Result (ParseOutcome (Clause0_Output × Clause1_Output))
  := do
  let po ← ParserInst.parse_with self.first input cursor status
  match po with
  | ParseOutcome.Success next first =>
    let po1 ← ParserInst1.parse_with self.second input next status
    match po1 with
    | ParseOutcome.Success «end» second =>
      ok (ParseOutcome.Success «end» (first, second))
    | ParseOutcome.Error error => ok (ParseOutcome.Error error)
    | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore
  | ParseOutcome.Error error => ok (ParseOutcome.Error error)
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, (Clause0_Output, Clause1_Output)> for rusthammer::Seq<P, Q>}]
    Source: 'src/lib.rs', lines 487:0-507:1 -/
@[reducible]
impl_def Seq.Insts.RusthammerParserInputPair {P : Type} {Q : Type}
  {Clause0_Output : Type} {Clause1_Output : Type} (ParserInst : Parser P
  Clause0_Output) (ParserInst1 : Parser Q Clause1_Output) : Parser (Seq P Q)
  (Clause0_Output × Clause1_Output) := {
  parse_with := Seq.Insts.RusthammerParserInputPair.parse_with ParserInst
    ParserInst1
  parse := Parser.parse.default (Seq.Insts.RusthammerParserInputPair ParserInst
    ParserInst1)
}

/-- [rusthammer::Left]
    Source: 'src/lib.rs', lines 513:0-516:1
    Visibility: public -/
structure Left (P : Type) (Q : Type) where
  first : P
  second : Q

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Left<P, Q>}::clone]:
    Source: 'src/lib.rs', lines 512:9-512:14
    Visibility: public -/
def Left.Insts.CoreCloneClone.clone
  {P : Type} {Q : Type} (corecloneCloneInst : core.clone.Clone P)
  (corecloneCloneInst1 : core.clone.Clone Q) (self : Left P Q) :
  Result (Left P Q)
  := do
  let t ← corecloneCloneInst.clone self.first
  let t1 ← corecloneCloneInst1.clone self.second
  ok { first := t, second := t1 }

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Left<P, Q>}]
    Source: 'src/lib.rs', lines 512:9-512:14 -/
@[reducible]
def Left.Insts.CoreCloneClone {P : Type} {Q : Type} (corecloneCloneInst :
  core.clone.Clone P) (corecloneCloneInst1 : core.clone.Clone Q) :
  core.clone.Clone (Left P Q) := {
  clone := Left.Insts.CoreCloneClone.clone corecloneCloneInst
    corecloneCloneInst1
}

/-- [rusthammer::{impl rusthammer::Parser<'input, Clause0_Output> for rusthammer::Left<P, Q>}::parse_with]:
    Source: 'src/lib.rs', lines 521:4-541:5
    Visibility: public -/
def Left.Insts.RusthammerParser.parse_with
  {P : Type} {Q : Type} {Clause0_Output : Type} {Clause1_Output : Type}
  (ParserInst : Parser P Clause0_Output) (ParserInst1 : Parser Q
  Clause1_Output) (self : Left P Q) (input : Slice Std.U8) (cursor : Cursor)
  (status : InputStatus) :
  Result (ParseOutcome Clause0_Output)
  := do
  let po ←
    Seq.Insts.RusthammerParserInputPair.parse_with
      (Shared0P.Insts.RusthammerParser ParserInst)
      (Shared0P.Insts.RusthammerParser ParserInst1)
      { first := self.first, second := self.second } input cursor status
  match po with
  | ParseOutcome.Success next values =>
    let (first, _) := values
    ok (ParseOutcome.Success next first)
  | ParseOutcome.Error error => ok (ParseOutcome.Error error)
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, Clause0_Output> for rusthammer::Left<P, Q>}]
    Source: 'src/lib.rs', lines 518:0-542:1 -/
@[reducible]
impl_def Left.Insts.RusthammerParser {P : Type} {Q : Type} {Clause0_Output :
  Type} {Clause1_Output : Type} (ParserInst : Parser P Clause0_Output)
  (ParserInst1 : Parser Q Clause1_Output) : Parser (Left P Q) Clause0_Output
  := {
  parse_with := Left.Insts.RusthammerParser.parse_with ParserInst ParserInst1
  parse := Parser.parse.default (Left.Insts.RusthammerParser ParserInst
    ParserInst1)
}

/-- [rusthammer::Right]
    Source: 'src/lib.rs', lines 548:0-551:1
    Visibility: public -/
structure Right (P : Type) (Q : Type) where
  first : P
  second : Q

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Right<P, Q>}::clone]:
    Source: 'src/lib.rs', lines 547:9-547:14
    Visibility: public -/
def Right.Insts.CoreCloneClone.clone
  {P : Type} {Q : Type} (corecloneCloneInst : core.clone.Clone P)
  (corecloneCloneInst1 : core.clone.Clone Q) (self : Right P Q) :
  Result (Right P Q)
  := do
  let t ← corecloneCloneInst.clone self.first
  let t1 ← corecloneCloneInst1.clone self.second
  ok { first := t, second := t1 }

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Right<P, Q>}]
    Source: 'src/lib.rs', lines 547:9-547:14 -/
@[reducible]
def Right.Insts.CoreCloneClone {P : Type} {Q : Type} (corecloneCloneInst :
  core.clone.Clone P) (corecloneCloneInst1 : core.clone.Clone Q) :
  core.clone.Clone (Right P Q) := {
  clone := Right.Insts.CoreCloneClone.clone corecloneCloneInst
    corecloneCloneInst1
}

/-- [rusthammer::{impl rusthammer::Parser<'input, Clause1_Output> for rusthammer::Right<P, Q>}::parse_with]:
    Source: 'src/lib.rs', lines 556:4-576:5
    Visibility: public -/
def Right.Insts.RusthammerParser.parse_with
  {P : Type} {Q : Type} {Clause0_Output : Type} {Clause1_Output : Type}
  (ParserInst : Parser P Clause0_Output) (ParserInst1 : Parser Q
  Clause1_Output) (self : Right P Q) (input : Slice Std.U8) (cursor : Cursor)
  (status : InputStatus) :
  Result (ParseOutcome Clause1_Output)
  := do
  let po ←
    Seq.Insts.RusthammerParserInputPair.parse_with
      (Shared0P.Insts.RusthammerParser ParserInst)
      (Shared0P.Insts.RusthammerParser ParserInst1)
      { first := self.first, second := self.second } input cursor status
  match po with
  | ParseOutcome.Success next values =>
    let (_, second) := values
    ok (ParseOutcome.Success next second)
  | ParseOutcome.Error error => ok (ParseOutcome.Error error)
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, Clause1_Output> for rusthammer::Right<P, Q>}]
    Source: 'src/lib.rs', lines 553:0-577:1 -/
@[reducible]
impl_def Right.Insts.RusthammerParser {P : Type} {Q : Type} {Clause0_Output :
  Type} {Clause1_Output : Type} (ParserInst : Parser P Clause0_Output)
  (ParserInst1 : Parser Q Clause1_Output) : Parser (Right P Q) Clause1_Output
  := {
  parse_with := Right.Insts.RusthammerParser.parse_with ParserInst ParserInst1
  parse := Parser.parse.default (Right.Insts.RusthammerParser ParserInst
    ParserInst1)
}

/-- [rusthammer::Middle]
    Source: 'src/lib.rs', lines 583:0-587:1
    Visibility: public -/
structure Middle (L : Type) (P : Type) (R : Type) where
  left : L
  parser : P
  right : R

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Middle<L, P, R>}::clone]:
    Source: 'src/lib.rs', lines 582:9-582:14
    Visibility: public -/
def Middle.Insts.CoreCloneClone.clone
  {L : Type} {P : Type} {R : Type} (corecloneCloneInst : core.clone.Clone L)
  (corecloneCloneInst1 : core.clone.Clone P) (corecloneCloneInst2 :
  core.clone.Clone R) (self : Middle L P R) :
  Result (Middle L P R)
  := do
  let t ← corecloneCloneInst.clone self.left
  let t1 ← corecloneCloneInst1.clone self.parser
  let t2 ← corecloneCloneInst2.clone self.right
  ok { left := t, parser := t1, right := t2 }

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Middle<L, P, R>}]
    Source: 'src/lib.rs', lines 582:9-582:14 -/
@[reducible]
def Middle.Insts.CoreCloneClone {L : Type} {P : Type} {R : Type}
  (corecloneCloneInst : core.clone.Clone L) (corecloneCloneInst1 :
  core.clone.Clone P) (corecloneCloneInst2 : core.clone.Clone R) :
  core.clone.Clone (Middle L P R) := {
  clone := Middle.Insts.CoreCloneClone.clone corecloneCloneInst
    corecloneCloneInst1 corecloneCloneInst2
}

/-- [rusthammer::{impl rusthammer::Parser<'input, Clause1_Output> for rusthammer::Middle<L, P, R>}::parse_with]:
    Source: 'src/lib.rs', lines 594:4-617:5
    Visibility: public -/
def Middle.Insts.RusthammerParser.parse_with
  {L : Type} {P : Type} {R : Type} {Clause0_Output : Type} {Clause1_Output :
  Type} {Clause2_Output : Type} (ParserInst : Parser L Clause0_Output)
  (ParserInst1 : Parser P Clause1_Output) (ParserInst2 : Parser R
  Clause2_Output) (self : Middle L P R) (input : Slice Std.U8)
  (cursor : Cursor) (status : InputStatus) :
  Result (ParseOutcome Clause1_Output)
  := do
  let po ←
    Seq.Insts.RusthammerParserInputPair.parse_with
      (Shared0P.Insts.RusthammerParser ParserInst)
      (Seq.Insts.RusthammerParserInputPair (Shared0P.Insts.RusthammerParser
      ParserInst1) (Shared0P.Insts.RusthammerParser ParserInst2))
      {
        first := self.left,
        second := { first := self.parser, second := self.right }
      } input cursor status
  match po with
  | ParseOutcome.Success next values =>
    let (_, (middle, _)) := values
    ok (ParseOutcome.Success next middle)
  | ParseOutcome.Error error => ok (ParseOutcome.Error error)
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, Clause1_Output> for rusthammer::Middle<L, P, R>}]
    Source: 'src/lib.rs', lines 589:0-618:1 -/
@[reducible]
impl_def Middle.Insts.RusthammerParser {L : Type} {P : Type} {R : Type}
  {Clause0_Output : Type} {Clause1_Output : Type} {Clause2_Output : Type}
  (ParserInst : Parser L Clause0_Output) (ParserInst1 : Parser P
  Clause1_Output) (ParserInst2 : Parser R Clause2_Output) : Parser (Middle L P
  R) Clause1_Output := {
  parse_with := Middle.Insts.RusthammerParser.parse_with ParserInst ParserInst1
    ParserInst2
  parse := Parser.parse.default (Middle.Insts.RusthammerParser ParserInst
    ParserInst1 ParserInst2)
}

/-- [rusthammer::Ignore]
    Source: 'src/lib.rs', lines 624:0-626:1
    Visibility: public -/
structure Ignore (P : Type) where
  parser : P

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Ignore<P>}::clone]:
    Source: 'src/lib.rs', lines 623:9-623:14
    Visibility: public -/
def Ignore.Insts.CoreCloneClone.clone
  {P : Type} (corecloneCloneInst : core.clone.Clone P) (self : Ignore P) :
  Result (Ignore P)
  := do
  let t ← corecloneCloneInst.clone self.parser
  ok { parser := t }

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Ignore<P>}]
    Source: 'src/lib.rs', lines 623:9-623:14 -/
@[reducible]
def Ignore.Insts.CoreCloneClone {P : Type} (corecloneCloneInst :
  core.clone.Clone P) : core.clone.Clone (Ignore P) := {
  clone := Ignore.Insts.CoreCloneClone.clone corecloneCloneInst
}

/-- [rusthammer::{impl rusthammer::Parser<'input, ()> for rusthammer::Ignore<P>}::parse_with]:
    Source: 'src/lib.rs', lines 631:4-642:5
    Visibility: public -/
def Ignore.Insts.RusthammerParserInputTuple.parse_with
  {P : Type} {Clause0_Output : Type} (ParserInst : Parser P Clause0_Output)
  (self : Ignore P) (input : Slice Std.U8) (cursor : Cursor)
  (status : InputStatus) :
  Result (ParseOutcome Unit)
  := do
  let po ← ParserInst.parse_with self.parser input cursor status
  match po with
  | ParseOutcome.Success next _ => ok (ParseOutcome.Success next ())
  | ParseOutcome.Error error => ok (ParseOutcome.Error error)
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, ()> for rusthammer::Ignore<P>}]
    Source: 'src/lib.rs', lines 628:0-643:1 -/
@[reducible]
impl_def Ignore.Insts.RusthammerParserInputTuple {P : Type} {Clause0_Output :
  Type} (ParserInst : Parser P Clause0_Output) : Parser (Ignore P) Unit := {
  parse_with := Ignore.Insts.RusthammerParserInputTuple.parse_with ParserInst
  parse := Parser.parse.default (Ignore.Insts.RusthammerParserInputTuple
    ParserInst)
}

/-- [rusthammer::Repeat]
    Source: 'src/lib.rs', lines 685:0-689:1
    Visibility: public -/
structure Repeat (P : Type) where
  parser : P
  min : Std.Usize
  max : Option Std.Usize

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Repeat<P>}::clone]:
    Source: 'src/lib.rs', lines 684:9-684:14
    Visibility: public -/
def Repeat.Insts.CoreCloneClone.clone
  {P : Type} (corecloneCloneInst : core.clone.Clone P) (self : Repeat P) :
  Result (Repeat P)
  := do
  let t ← corecloneCloneInst.clone self.parser
  let i ← lift (core.clone.impls.CloneUsize.clone self.min)
  let o ←
    core.option.Option.Insts.CoreCloneClone.clone core.clone.CloneUsize
      self.max
  ok { parser := t, min := i, max := o }

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Repeat<P>}]
    Source: 'src/lib.rs', lines 684:9-684:14 -/
@[reducible]
def Repeat.Insts.CoreCloneClone {P : Type} (corecloneCloneInst :
  core.clone.Clone P) : core.clone.Clone (Repeat P) := {
  clone := Repeat.Insts.CoreCloneClone.clone corecloneCloneInst
}

/-- [rusthammer::{rusthammer::Repeat<P>}::new]:
    Source: 'src/lib.rs', lines 694:4-704:5
    Visibility: public -/
def Repeat.new
  {P : Type} (parser : P) (min : Std.Usize) (max : Std.Usize) :
  Result (core.result.Result (Repeat P) ConfigError)
  := do
  if min > max
  then ok (core.result.Result.Err ConfigError.InvalidBounds)
  else ok (core.result.Result.Ok { parser, min, max := (some max) })

/-- [rusthammer::{rusthammer::Repeat<P>}::exact]:
    Source: 'src/lib.rs', lines 707:4-713:5
    Visibility: public -/
def Repeat.exact
  {P : Type} (parser : P) (count : Std.Usize) : Result (Repeat P) := do
  ok { parser, min := count, max := (some count) }

/-- [rusthammer::{rusthammer::Repeat<P>}::at_least]:
    Source: 'src/lib.rs', lines 718:4-724:5
    Visibility: public -/
def Repeat.at_least
  {P : Type} (parser : P) (min : Std.Usize) : Result (Repeat P) := do
  ok { parser, min, max := none }

/-- [rusthammer::{rusthammer::Repeat<P>}::min]:
    Source: 'src/lib.rs', lines 727:4-729:5
    Visibility: public -/
def Repeat.impl.min {P : Type} (self : Repeat P) : Result Std.Usize := do
  ok self.min

/-- [rusthammer::{rusthammer::Repeat<P>}::max]:
    Source: 'src/lib.rs', lines 732:4-734:5
    Visibility: public -/
def Repeat.impl.max
  {P : Type} (self : Repeat P) : Result (Option Std.Usize) := do
  ok self.max

/-- [rusthammer::repeat_cursor_valid]:
    Source: 'src/lib.rs', lines 739:0-741:1 -/
def repeat_cursor_valid
  (input : Slice Std.U8) (cursor : Cursor) : Result Bool := do
  if cursor.bit < 8#u8
  then
    let i := Slice.len input
    if cursor.byte < i
    then ok true
    else
      let i1 := Slice.len input
      if cursor.byte = i1
      then ok (cursor.bit = 0#u8)
      else ok false
  else ok false

/-- [rusthammer::repeat_start]:
    Source: 'src/lib.rs', lines 744:0-750:1 -/
def repeat_start
  (input : Slice Std.U8) (cursor : Cursor) (unbounded : Bool) :
  Result (core.result.Result Unit ParseError)
  := do
  if unbounded
  then
    let b ← repeat_cursor_valid input cursor
    if b
    then ok (core.result.Result.Ok ())
    else ok (core.result.Result.Err ParseError.InvalidCursor)
  else ok (core.result.Result.Ok ())

/-- [rusthammer::repeat_below_max]:
    Source: 'src/lib.rs', lines 753:0-758:1 -/
def repeat_below_max
  (count : Std.Usize) (max : Option Std.Usize) : Result Bool := do
  match max with
  | none => ok true
  | some max1 => ok (count < max1)

/-- [rusthammer::repeat_progress]:
    Source: 'src/lib.rs', lines 761:0-769:1 -/
def repeat_progress
  (input : Slice Std.U8) (before : Cursor) (after : Cursor) :
  Result (core.result.Result Unit ParseError)
  := do
  let b ← repeat_cursor_valid input after
  if b
  then
    if after.byte < before.byte
    then ok (core.result.Result.Err ParseError.NonProgress)
    else
      if after.byte = before.byte
      then
        if after.bit <= before.bit
        then ok (core.result.Result.Err ParseError.NonProgress)
        else ok (core.result.Result.Ok ())
      else ok (core.result.Result.Ok ())
  else ok (core.result.Result.Err ParseError.InvalidCursor)

/-- [rusthammer::repeat_next_count]:
    Source: 'src/lib.rs', lines 772:0-778:1 -/
def repeat_next_count
  (count : Std.Usize) : Result (core.result.Result Std.Usize ParseError) := do
  if count = core.num.Usize.MAX
  then ok (core.result.Result.Err ParseError.CountOverflow)
  else let i ← count + 1#usize
       ok (core.result.Result.Ok i)

/-- [rusthammer::{impl rusthammer::Parser<'input, alloc::vec::Vec<Clause0_Output>> for rusthammer::Repeat<P>}::parse_with]: loop body 0:
    Source: 'src/lib.rs', lines 1:0-825:9
    Visibility: public -/
@[rust_loop_body]
def Repeat.Insts.RusthammerParserInputVec.parse_with_loop.body
  {P : Type} {Clause0_Output : Type} (ParserInst : Parser P Clause0_Output)
  (t : P) (i : Std.Usize) (o : Option Std.Usize) (input : Slice Std.U8)
  (status : InputStatus) (unbounded : Bool)
  (values : alloc.vec.Vec Clause0_Output) (next : Cursor) (count : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Clause0_Output) × Cursor × Std.Usize)
    (ParseOutcome (alloc.vec.Vec Clause0_Output)))
  := do
  let b ← repeat_below_max count o
  if b
  then
    let po ← ParserInst.parse_with t input next status
    match po with
    | ParseOutcome.Success after value =>
      if unbounded
      then
        let r ← repeat_progress input next after
        match r with
        | core.result.Result.Ok _ =>
          let r1 ← repeat_next_count count
          match r1 with
          | core.result.Result.Ok count1 =>
            let values1 ← alloc.vec.Vec.push values value
            ok (cont (values1, after, count1))
          | core.result.Result.Err error =>
            ok (done (ParseOutcome.Error error))
        | core.result.Result.Err error => ok (done (ParseOutcome.Error error))
      else
        let r ← repeat_next_count count
        match r with
        | core.result.Result.Ok count1 =>
          let values1 ← alloc.vec.Vec.push values value
          ok (cont (values1, after, count1))
        | core.result.Result.Err error => ok (done (ParseOutcome.Error error))
    | ParseOutcome.Error error =>
      if count >= i
      then
        let b1 ← ParseError.is_recoverable error
        if b1
        then ok (done (ParseOutcome.Success next values))
        else ok (done (ParseOutcome.Error error))
      else ok (done (ParseOutcome.Error error))
    | ParseOutcome.NeedMore => ok (done ParseOutcome.NeedMore)
  else ok (done (ParseOutcome.Success next values))

/-- [rusthammer::{impl rusthammer::Parser<'input, alloc::vec::Vec<Clause0_Output>> for rusthammer::Repeat<P>}::parse_with]: loop 0:
    Source: 'src/lib.rs', lines 1:0-825:9
    Visibility: public -/
@[rust_loop]
def Repeat.Insts.RusthammerParserInputVec.parse_with_loop
  {P : Type} {Clause0_Output : Type} (ParserInst : Parser P Clause0_Output)
  (t : P) (i : Std.Usize) (o : Option Std.Usize) (input : Slice Std.U8)
  (status : InputStatus) (unbounded : Bool)
  (values : alloc.vec.Vec Clause0_Output) (next : Cursor) (count : Std.Usize) :
  Result (ParseOutcome (alloc.vec.Vec Clause0_Output))
  := do
  loop
    (fun (values1, next1, count1) =>
      Repeat.Insts.RusthammerParserInputVec.parse_with_loop.body ParserInst t i
      o input status unbounded values1 next1 count1)
    (values, next, count)

/-- [rusthammer::{impl rusthammer::Parser<'input, alloc::vec::Vec<Clause0_Output>> for rusthammer::Repeat<P>}::parse_with]:
    Source: 'src/lib.rs', lines 784:4-826:5
    Visibility: public -/
def Repeat.Insts.RusthammerParserInputVec.parse_with
  {P : Type} {Clause0_Output : Type} (ParserInst : Parser P Clause0_Output)
  (self : Repeat P) (input : Slice Std.U8) (cursor : Cursor)
  (status : InputStatus) :
  Result (ParseOutcome (alloc.vec.Vec Clause0_Output))
  := do
  let unbounded := core.option.Option.is_none self.max
  let r ← repeat_start input cursor unbounded
  match r with
  | core.result.Result.Ok _ =>
    Repeat.Insts.RusthammerParserInputVec.parse_with_loop ParserInst
      self.parser self.min self.max input status unbounded (alloc.vec.Vec.new
      Clause0_Output) cursor 0#usize
  | core.result.Result.Err error => ok (ParseOutcome.Error error)

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, alloc::vec::Vec<Clause0_Output>> for rusthammer::Repeat<P>}]
    Source: 'src/lib.rs', lines 781:0-827:1 -/
@[reducible]
impl_def Repeat.Insts.RusthammerParserInputVec {P : Type} {Clause0_Output :
  Type} (ParserInst : Parser P Clause0_Output) : Parser (Repeat P)
  (alloc.vec.Vec Clause0_Output) := {
  parse_with := Repeat.Insts.RusthammerParserInputVec.parse_with ParserInst
  parse := Parser.parse.default (Repeat.Insts.RusthammerParserInputVec
    ParserInst)
}

/-- [rusthammer::Map]
    Source: 'src/lib.rs', lines 836:0-839:1
    Visibility: public -/
structure Map (P : Type) (F : Type) where
  parser : P
  map : F

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Map<P, F>}::clone]:
    Source: 'src/lib.rs', lines 835:9-835:14
    Visibility: public -/
def Map.Insts.CoreCloneClone.clone
  {P : Type} {F : Type} (corecloneCloneInst : core.clone.Clone P)
  (corecloneCloneInst1 : core.clone.Clone F) (self : Map P F) :
  Result (Map P F)
  := do
  let t ← corecloneCloneInst.clone self.parser
  let t1 ← corecloneCloneInst1.clone self.map
  ok { parser := t, map := t1 }

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Map<P, F>}]
    Source: 'src/lib.rs', lines 835:9-835:14 -/
@[reducible]
def Map.Insts.CoreCloneClone {P : Type} {F : Type} (corecloneCloneInst :
  core.clone.Clone P) (corecloneCloneInst1 : core.clone.Clone F) :
  core.clone.Clone (Map P F) := {
  clone := Map.Insts.CoreCloneClone.clone corecloneCloneInst
    corecloneCloneInst1
}

/-- [rusthammer::{impl rusthammer::Parser<'input, O> for rusthammer::Map<P, F>}::parse_with]:
    Source: 'src/lib.rs', lines 848:4-859:5
    Visibility: public -/
def Map.Insts.RusthammerParser.parse_with
  {P : Type} {F : Type} {O : Type} {Clause0_Output : Type} (ParserInst : Parser
  P Clause0_Output) (coreopsfunctionFnFTupleClause0_OutputOInst :
  core.ops.function.Fn F Clause0_Output O) (self : Map P F)
  (input : Slice Std.U8) (cursor : Cursor) (status : InputStatus) :
  Result (ParseOutcome O)
  := do
  let po ← ParserInst.parse_with self.parser input cursor status
  match po with
  | ParseOutcome.Success next value =>
    let t ← coreopsfunctionFnFTupleClause0_OutputOInst.call self.map value
    ok (ParseOutcome.Success next t)
  | ParseOutcome.Error error => ok (ParseOutcome.Error error)
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, O> for rusthammer::Map<P, F>}]
    Source: 'src/lib.rs', lines 841:0-860:1 -/
@[reducible]
impl_def Map.Insts.RusthammerParser {P : Type} {F : Type} {O : Type}
  {Clause0_Output : Type} (ParserInst : Parser P Clause0_Output)
  (coreopsfunctionFnFTupleClause0_OutputOInst : core.ops.function.Fn F
  Clause0_Output O) : Parser (Map P F) O := {
  parse_with := Map.Insts.RusthammerParser.parse_with ParserInst
    coreopsfunctionFnFTupleClause0_OutputOInst
  parse := Parser.parse.default (Map.Insts.RusthammerParser ParserInst
    coreopsfunctionFnFTupleClause0_OutputOInst)
}

/-- [rusthammer::TryMap]
    Source: 'src/lib.rs', lines 872:0-875:1
    Visibility: public -/
structure TryMap (P : Type) (F : Type) where
  parser : P
  map : F

/-- [rusthammer::{impl core::clone::Clone for rusthammer::TryMap<P, F>}::clone]:
    Source: 'src/lib.rs', lines 871:9-871:14
    Visibility: public -/
def TryMap.Insts.CoreCloneClone.clone
  {P : Type} {F : Type} (corecloneCloneInst : core.clone.Clone P)
  (corecloneCloneInst1 : core.clone.Clone F) (self : TryMap P F) :
  Result (TryMap P F)
  := do
  let t ← corecloneCloneInst.clone self.parser
  let t1 ← corecloneCloneInst1.clone self.map
  ok { parser := t, map := t1 }

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::TryMap<P, F>}]
    Source: 'src/lib.rs', lines 871:9-871:14 -/
@[reducible]
def TryMap.Insts.CoreCloneClone {P : Type} {F : Type} (corecloneCloneInst :
  core.clone.Clone P) (corecloneCloneInst1 : core.clone.Clone F) :
  core.clone.Clone (TryMap P F) := {
  clone := TryMap.Insts.CoreCloneClone.clone corecloneCloneInst
    corecloneCloneInst1
}

/-- [rusthammer::{impl rusthammer::Parser<'input, O> for rusthammer::TryMap<P, F>}::parse_with]:
    Source: 'src/lib.rs', lines 884:4-901:5
    Visibility: public -/
def TryMap.Insts.RusthammerParser.parse_with
  {P : Type} {F : Type} {O : Type} {E : Type} {Clause0_Output : Type}
  (ParserInst : Parser P Clause0_Output)
  (coreopsfunctionFnFTupleClause0_OutputResultInst : core.ops.function.Fn F
  Clause0_Output (core.result.Result O E)) (self : TryMap P F)
  (input : Slice Std.U8) (cursor : Cursor) (status : InputStatus) :
  Result (ParseOutcome O)
  := do
  let po ← ParserInst.parse_with self.parser input cursor status
  match po with
  | ParseOutcome.Success next value =>
    let r ←
      coreopsfunctionFnFTupleClause0_OutputResultInst.call self.map value
    match r with
    | core.result.Result.Ok mapped => ok (ParseOutcome.Success next mapped)
    | core.result.Result.Err _ => ok (ParseOutcome.Error ParseError.Mismatch)
  | ParseOutcome.Error error => ok (ParseOutcome.Error error)
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, O> for rusthammer::TryMap<P, F>}]
    Source: 'src/lib.rs', lines 877:0-902:1 -/
@[reducible]
impl_def TryMap.Insts.RusthammerParser {P : Type} {F : Type} {O : Type} {E :
  Type} {Clause0_Output : Type} (ParserInst : Parser P Clause0_Output)
  (coreopsfunctionFnFTupleClause0_OutputResultInst : core.ops.function.Fn F
  Clause0_Output (core.result.Result O E)) : Parser (TryMap P F) O := {
  parse_with := TryMap.Insts.RusthammerParser.parse_with ParserInst
    coreopsfunctionFnFTupleClause0_OutputResultInst
  parse := Parser.parse.default (TryMap.Insts.RusthammerParser ParserInst
    coreopsfunctionFnFTupleClause0_OutputResultInst)
}

/-- [rusthammer::Verify]
    Source: 'src/lib.rs', lines 911:0-914:1
    Visibility: public -/
structure Verify (P : Type) (F : Type) where
  parser : P
  predicate : F

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Verify<P, F>}::clone]:
    Source: 'src/lib.rs', lines 910:9-910:14
    Visibility: public -/
def Verify.Insts.CoreCloneClone.clone
  {P : Type} {F : Type} (corecloneCloneInst : core.clone.Clone P)
  (corecloneCloneInst1 : core.clone.Clone F) (self : Verify P F) :
  Result (Verify P F)
  := do
  let t ← corecloneCloneInst.clone self.parser
  let t1 ← corecloneCloneInst1.clone self.predicate
  ok { parser := t, predicate := t1 }

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Verify<P, F>}]
    Source: 'src/lib.rs', lines 910:9-910:14 -/
@[reducible]
def Verify.Insts.CoreCloneClone {P : Type} {F : Type} (corecloneCloneInst :
  core.clone.Clone P) (corecloneCloneInst1 : core.clone.Clone F) :
  core.clone.Clone (Verify P F) := {
  clone := Verify.Insts.CoreCloneClone.clone corecloneCloneInst
    corecloneCloneInst1
}

/-- [rusthammer::{impl rusthammer::Parser<'input, Clause0_Output> for rusthammer::Verify<P, F>}::parse_with]:
    Source: 'src/lib.rs', lines 923:4-940:5
    Visibility: public -/
def Verify.Insts.RusthammerParser.parse_with
  {P : Type} {F : Type} {Clause0_Output : Type} (ParserInst : Parser P
  Clause0_Output) (coreopsfunctionFnFTupleSharedInputClause0_OutputBoolInst :
  core.ops.function.Fn F Clause0_Output Bool) (self : Verify P F)
  (input : Slice Std.U8) (cursor : Cursor) (status : InputStatus) :
  Result (ParseOutcome Clause0_Output)
  := do
  let po ← ParserInst.parse_with self.parser input cursor status
  match po with
  | ParseOutcome.Success _ value =>
    let b ←
      coreopsfunctionFnFTupleSharedInputClause0_OutputBoolInst.call
        self.predicate value
    if b
    then ok po
    else ok (ParseOutcome.Error ParseError.Mismatch)
  | ParseOutcome.Error _ => ok po
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, Clause0_Output> for rusthammer::Verify<P, F>}]
    Source: 'src/lib.rs', lines 916:0-941:1 -/
@[reducible]
impl_def Verify.Insts.RusthammerParser {P : Type} {F : Type} {Clause0_Output :
  Type} (ParserInst : Parser P Clause0_Output)
  (coreopsfunctionFnFTupleSharedInputClause0_OutputBoolInst :
  core.ops.function.Fn F Clause0_Output Bool) : Parser (Verify P F)
  Clause0_Output := {
  parse_with := Verify.Insts.RusthammerParser.parse_with ParserInst
    coreopsfunctionFnFTupleSharedInputClause0_OutputBoolInst
  parse := Parser.parse.default (Verify.Insts.RusthammerParser ParserInst
    coreopsfunctionFnFTupleSharedInputClause0_OutputBoolInst)
}

/-- [rusthammer::Choice]
    Source: 'src/lib.rs', lines 951:0-954:1
    Visibility: public -/
structure Choice (P : Type) (Q : Type) where
  first : P
  second : Q

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Choice<P, Q>}::clone]:
    Source: 'src/lib.rs', lines 950:9-950:14
    Visibility: public -/
def Choice.Insts.CoreCloneClone.clone
  {P : Type} {Q : Type} (corecloneCloneInst : core.clone.Clone P)
  (corecloneCloneInst1 : core.clone.Clone Q) (self : Choice P Q) :
  Result (Choice P Q)
  := do
  let t ← corecloneCloneInst.clone self.first
  let t1 ← corecloneCloneInst1.clone self.second
  ok { first := t, second := t1 }

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Choice<P, Q>}]
    Source: 'src/lib.rs', lines 950:9-950:14 -/
@[reducible]
def Choice.Insts.CoreCloneClone {P : Type} {Q : Type} (corecloneCloneInst :
  core.clone.Clone P) (corecloneCloneInst1 : core.clone.Clone Q) :
  core.clone.Clone (Choice P Q) := {
  clone := Choice.Insts.CoreCloneClone.clone corecloneCloneInst
    corecloneCloneInst1
}

/-- [rusthammer::{impl rusthammer::Parser<'input, Clause0_Output> for rusthammer::Choice<P, Q>}::parse_with]:
    Source: 'src/lib.rs', lines 963:4-980:5
    Visibility: public -/
def Choice.Insts.RusthammerParser.parse_with
  {P : Type} {Q : Type} {Clause0_Output : Type} (ParserInst : Parser P
  Clause0_Output) (ParserInst1 : Parser Q Clause0_Output) (self : Choice P Q)
  (input : Slice Std.U8) (cursor : Cursor) (status : InputStatus) :
  Result (ParseOutcome Clause0_Output)
  := do
  let po ← ParserInst.parse_with self.first input cursor status
  match po with
  | ParseOutcome.Success _ _ => ok po
  | ParseOutcome.Error error =>
    let b ← ParseError.is_recoverable error
    if b
    then ParserInst1.parse_with self.second input cursor status
    else ok po
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, Clause0_Output> for rusthammer::Choice<P, Q>}]
    Source: 'src/lib.rs', lines 956:0-981:1 -/
@[reducible]
impl_def Choice.Insts.RusthammerParser {P : Type} {Q : Type} {Clause0_Output :
  Type} (ParserInst : Parser P Clause0_Output) (ParserInst1 : Parser Q
  Clause0_Output) : Parser (Choice P Q) Clause0_Output := {
  parse_with := Choice.Insts.RusthammerParser.parse_with ParserInst ParserInst1
  parse := Parser.parse.default (Choice.Insts.RusthammerParser ParserInst
    ParserInst1)
}

/-- [rusthammer::Optional]
    Source: 'src/lib.rs', lines 990:0-992:1
    Visibility: public -/
structure Optional (P : Type) where
  parser : P

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Optional<P>}::clone]:
    Source: 'src/lib.rs', lines 989:9-989:14
    Visibility: public -/
def Optional.Insts.CoreCloneClone.clone
  {P : Type} (corecloneCloneInst : core.clone.Clone P) (self : Optional P) :
  Result (Optional P)
  := do
  let t ← corecloneCloneInst.clone self.parser
  ok { parser := t }

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Optional<P>}]
    Source: 'src/lib.rs', lines 989:9-989:14 -/
@[reducible]
def Optional.Insts.CoreCloneClone {P : Type} (corecloneCloneInst :
  core.clone.Clone P) : core.clone.Clone (Optional P) := {
  clone := Optional.Insts.CoreCloneClone.clone corecloneCloneInst
}

/-- [rusthammer::{impl rusthammer::Parser<'input, core::option::Option<Clause0_Output>> for rusthammer::Optional<P>}::parse_with]:
    Source: 'src/lib.rs', lines 997:4-1014:5
    Visibility: public -/
def Optional.Insts.RusthammerParserInputOption.parse_with
  {P : Type} {Clause0_Output : Type} (ParserInst : Parser P Clause0_Output)
  (self : Optional P) (input : Slice Std.U8) (cursor : Cursor)
  (status : InputStatus) :
  Result (ParseOutcome (Option Clause0_Output))
  := do
  let po ← ParserInst.parse_with self.parser input cursor status
  match po with
  | ParseOutcome.Success next value =>
    ok (ParseOutcome.Success next (some value))
  | ParseOutcome.Error error =>
    let b ← ParseError.is_recoverable error
    if b
    then ok (ParseOutcome.Success cursor none)
    else ok (ParseOutcome.Error error)
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, core::option::Option<Clause0_Output>> for rusthammer::Optional<P>}]
    Source: 'src/lib.rs', lines 994:0-1015:1 -/
@[reducible]
impl_def Optional.Insts.RusthammerParserInputOption {P : Type} {Clause0_Output
  : Type} (ParserInst : Parser P Clause0_Output) : Parser (Optional P) (Option
  Clause0_Output) := {
  parse_with := Optional.Insts.RusthammerParserInputOption.parse_with
    ParserInst
  parse := Parser.parse.default (Optional.Insts.RusthammerParserInputOption
    ParserInst)
}

/-- [rusthammer::And]
    Source: 'src/lib.rs', lines 1023:0-1025:1
    Visibility: public -/
structure And (P : Type) where
  parser : P

/-- [rusthammer::{impl core::clone::Clone for rusthammer::And<P>}::clone]:
    Source: 'src/lib.rs', lines 1022:9-1022:14
    Visibility: public -/
def And.Insts.CoreCloneClone.clone
  {P : Type} (corecloneCloneInst : core.clone.Clone P) (self : And P) :
  Result (And P)
  := do
  let t ← corecloneCloneInst.clone self.parser
  ok { parser := t }

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::And<P>}]
    Source: 'src/lib.rs', lines 1022:9-1022:14 -/
@[reducible]
def And.Insts.CoreCloneClone {P : Type} (corecloneCloneInst : core.clone.Clone
  P) : core.clone.Clone (And P) := {
  clone := And.Insts.CoreCloneClone.clone corecloneCloneInst
}

/-- [rusthammer::{impl rusthammer::Parser<'input, ()> for rusthammer::And<P>}::parse_with]:
    Source: 'src/lib.rs', lines 1030:4-1041:5
    Visibility: public -/
def And.Insts.RusthammerParserInputTuple.parse_with
  {P : Type} {Clause0_Output : Type} (ParserInst : Parser P Clause0_Output)
  (self : And P) (input : Slice Std.U8) (cursor : Cursor)
  (status : InputStatus) :
  Result (ParseOutcome Unit)
  := do
  let po ← ParserInst.parse_with self.parser input cursor status
  match po with
  | ParseOutcome.Success _ _ => ok (ParseOutcome.Success cursor ())
  | ParseOutcome.Error error => ok (ParseOutcome.Error error)
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, ()> for rusthammer::And<P>}]
    Source: 'src/lib.rs', lines 1027:0-1042:1 -/
@[reducible]
impl_def And.Insts.RusthammerParserInputTuple {P : Type} {Clause0_Output :
  Type} (ParserInst : Parser P Clause0_Output) : Parser (And P) Unit := {
  parse_with := And.Insts.RusthammerParserInputTuple.parse_with ParserInst
  parse := Parser.parse.default (And.Insts.RusthammerParserInputTuple
    ParserInst)
}

/-- [rusthammer::Not]
    Source: 'src/lib.rs', lines 1050:0-1052:1
    Visibility: public -/
structure Not (P : Type) where
  parser : P

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Not<P>}::clone]:
    Source: 'src/lib.rs', lines 1049:9-1049:14
    Visibility: public -/
def Not.Insts.CoreCloneClone.clone
  {P : Type} (corecloneCloneInst : core.clone.Clone P) (self : Not P) :
  Result (Not P)
  := do
  let t ← corecloneCloneInst.clone self.parser
  ok { parser := t }

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Not<P>}]
    Source: 'src/lib.rs', lines 1049:9-1049:14 -/
@[reducible]
def Not.Insts.CoreCloneClone {P : Type} (corecloneCloneInst : core.clone.Clone
  P) : core.clone.Clone (Not P) := {
  clone := Not.Insts.CoreCloneClone.clone corecloneCloneInst
}

/-- [rusthammer::{impl rusthammer::Parser<'input, ()> for rusthammer::Not<P>}::parse_with]:
    Source: 'src/lib.rs', lines 1057:4-1074:5
    Visibility: public -/
def Not.Insts.RusthammerParserInputTuple.parse_with
  {P : Type} {Clause0_Output : Type} (ParserInst : Parser P Clause0_Output)
  (self : Not P) (input : Slice Std.U8) (cursor : Cursor)
  (status : InputStatus) :
  Result (ParseOutcome Unit)
  := do
  let po ← ParserInst.parse_with self.parser input cursor status
  match po with
  | ParseOutcome.Success _ _ => ok (ParseOutcome.Error ParseError.Mismatch)
  | ParseOutcome.Error error =>
    let b ← ParseError.is_recoverable error
    if b
    then ok (ParseOutcome.Success cursor ())
    else ok (ParseOutcome.Error error)
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, ()> for rusthammer::Not<P>}]
    Source: 'src/lib.rs', lines 1054:0-1075:1 -/
@[reducible]
impl_def Not.Insts.RusthammerParserInputTuple {P : Type} {Clause0_Output :
  Type} (ParserInst : Parser P Clause0_Output) : Parser (Not P) Unit := {
  parse_with := Not.Insts.RusthammerParserInputTuple.parse_with ParserInst
  parse := Parser.parse.default (Not.Insts.RusthammerParserInputTuple
    ParserInst)
}

/-- [rusthammer::TakeAligned]
    Source: 'src/lib.rs', lines 1082:0-1084:1
    Visibility: public -/
structure TakeAligned where
  count : Std.Usize

/-- [rusthammer::{impl core::clone::Clone for rusthammer::TakeAligned}::clone]:
    Source: 'src/lib.rs', lines 1081:9-1081:14
    Visibility: public -/
def TakeAligned.Insts.CoreCloneClone.clone
  (self : TakeAligned) : Result TakeAligned := do
  ok self

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::TakeAligned}]
    Source: 'src/lib.rs', lines 1081:9-1081:14 -/
@[reducible]
def TakeAligned.Insts.CoreCloneClone : core.clone.Clone TakeAligned := {
  clone := TakeAligned.Insts.CoreCloneClone.clone
}

/-- [rusthammer::take_aligned]:
    Source: 'src/lib.rs', lines 1127:0-1146:1
    Visibility: public -/
def take_aligned
  (input : Slice Std.U8) (cursor : Cursor) (count : Std.Usize) :
  Result (core.result.Result (Cursor × (Slice Std.U8)) ParseError)
  := do
  if cursor.bit >= 8#u8
  then ok (core.result.Result.Err ParseError.InvalidCursor)
  else
    let i := Slice.len input
    if cursor.byte > i
    then ok (core.result.Result.Err ParseError.InvalidCursor)
    else
      let i1 := Slice.len input
      if cursor.byte = i1
      then
        if cursor.bit != 0#u8
        then ok (core.result.Result.Err ParseError.InvalidCursor)
        else
          if cursor.bit != 0#u8
          then ok (core.result.Result.Err ParseError.Unaligned)
          else
            let i2 := Slice.len input
            let i3 ← i2 - cursor.byte
            if count > i3
            then ok (core.result.Result.Err ParseError.UnexpectedEnd)
            else
              let «end» ← cursor.byte + count
              let s ←
                core.slice.index.Slice.index
                  (core.slice.index.SliceIndexRangeUsizeSlice Std.U8) input
                  { start := cursor.byte, «end» }
              ok (core.result.Result.Ok ({ byte := «end», bit := 0#u8 }, s))
      else
        if cursor.bit != 0#u8
        then ok (core.result.Result.Err ParseError.Unaligned)
        else
          let i2 := Slice.len input
          let i3 ← i2 - cursor.byte
          if count > i3
          then ok (core.result.Result.Err ParseError.UnexpectedEnd)
          else
            let «end» ← cursor.byte + count
            let s ←
              core.slice.index.Slice.index
                (core.slice.index.SliceIndexRangeUsizeSlice Std.U8) input
                { start := cursor.byte, «end» }
            ok (core.result.Result.Ok ({ byte := «end», bit := 0#u8 }, s))

/-- [rusthammer::{impl rusthammer::Parser<'input, &'input [u8]> for rusthammer::TakeAligned}::parse_with]:
    Source: 'src/lib.rs', lines 1089:4-1096:5
    Visibility: public -/
def TakeAligned.Insts.RusthammerParserInputSharedInputSliceU8.parse_with
  (self : TakeAligned) (input : Slice Std.U8) (cursor : Cursor)
  (status : InputStatus) :
  Result (ParseOutcome (Slice Std.U8))
  := do
  let r ← take_aligned input cursor self.count
  InputStatus.classify status r

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, &'input [u8]> for rusthammer::TakeAligned}]
    Source: 'src/lib.rs', lines 1086:0-1097:1 -/
@[reducible]
impl_def TakeAligned.Insts.RusthammerParserInputSharedInputSliceU8 : Parser
  TakeAligned (Slice Std.U8) := {
  parse_with :=
    TakeAligned.Insts.RusthammerParserInputSharedInputSliceU8.parse_with
  parse := Parser.parse.default
    TakeAligned.Insts.RusthammerParserInputSharedInputSliceU8
}

/-- [rusthammer::Flags]
    Source: 'src/lib.rs', lines 1101:0-1105:1
    Visibility: public -/
structure Flags where
  urgent : Bool
  encrypted : Bool
  compressed : Bool

/-- [rusthammer::parse_flags::{closure}]
    Source: 'src/lib.rs', lines 1117:13-1121:9 -/
@[reducible]
def parse_flags.closure := Unit

/-- [rusthammer::parse_flags::{impl core::ops::function::Fn<((bool, (bool, bool)),), rusthammer::Flags> for rusthammer::parse_flags::{closure}}::call]:
    Source: 'src/lib.rs', lines 1117:13-1121:9 -/
def
  parse_flags.closure.Insts.CoreOpsFunctionFnTuplePairBoolPairBoolBoolFlags.call
  (c : parse_flags.closure) (tupled_args : (Bool × (Bool × Bool))) :
  Result Flags
  := do
  let (urgent, (encrypted, compressed)) := tupled_args
  ok { urgent, encrypted, compressed }

/-- [rusthammer::parse_flags::{impl core::ops::function::FnMut<((bool, (bool, bool)),), rusthammer::Flags> for rusthammer::parse_flags::{closure}}::call_mut]:
    Source: 'src/lib.rs', lines 1117:13-1121:9 -/
def
  parse_flags.closure.Insts.CoreOpsFunctionFnMutTuplePairBoolPairBoolBoolFlags.call_mut
  (state : parse_flags.closure) (args : (Bool × (Bool × Bool))) :
  Result (Flags × parse_flags.closure)
  := do
  let f ←
    parse_flags.closure.Insts.CoreOpsFunctionFnTuplePairBoolPairBoolBoolFlags.call
      state args
  ok (f, state)

/-- [rusthammer::parse_flags::{impl core::ops::function::FnOnce<((bool, (bool, bool)),), rusthammer::Flags> for rusthammer::parse_flags::{closure}}::call_once]:
    Source: 'src/lib.rs', lines 1117:13-1121:9 -/
def
  parse_flags.closure.Insts.CoreOpsFunctionFnOnceTuplePairBoolPairBoolBoolFlags.call_once
  (c : parse_flags.closure) (p : (Bool × (Bool × Bool))) : Result Flags := do
  let (f, _) ←
    parse_flags.closure.Insts.CoreOpsFunctionFnMutTuplePairBoolPairBoolBoolFlags.call_mut
      c p
  ok f

/-- Trait implementation: [rusthammer::parse_flags::{impl core::ops::function::FnOnce<((bool, (bool, bool)),), rusthammer::Flags> for rusthammer::parse_flags::{closure}}]
    Source: 'src/lib.rs', lines 1117:13-1121:9 -/
@[reducible]
def
  parse_flags.closure.Insts.CoreOpsFunctionFnOnceTuplePairBoolPairBoolBoolFlags
  : core.ops.function.FnOnce parse_flags.closure (Bool × (Bool × Bool)) Flags
  := {
  call_once :=
    parse_flags.closure.Insts.CoreOpsFunctionFnOnceTuplePairBoolPairBoolBoolFlags.call_once
}

/-- Trait implementation: [rusthammer::parse_flags::{impl core::ops::function::FnMut<((bool, (bool, bool)),), rusthammer::Flags> for rusthammer::parse_flags::{closure}}]
    Source: 'src/lib.rs', lines 1117:13-1121:9 -/
@[reducible]
def
  parse_flags.closure.Insts.CoreOpsFunctionFnMutTuplePairBoolPairBoolBoolFlags
  : core.ops.function.FnMut parse_flags.closure (Bool × (Bool × Bool)) Flags
  := {
  FnOnceInst :=
    parse_flags.closure.Insts.CoreOpsFunctionFnOnceTuplePairBoolPairBoolBoolFlags
  call_mut :=
    parse_flags.closure.Insts.CoreOpsFunctionFnMutTuplePairBoolPairBoolBoolFlags.call_mut
}

/-- Trait implementation: [rusthammer::parse_flags::{impl core::ops::function::Fn<((bool, (bool, bool)),), rusthammer::Flags> for rusthammer::parse_flags::{closure}}]
    Source: 'src/lib.rs', lines 1117:13-1121:9 -/
@[reducible]
def parse_flags.closure.Insts.CoreOpsFunctionFnTuplePairBoolPairBoolBoolFlags :
  core.ops.function.Fn parse_flags.closure (Bool × (Bool × Bool)) Flags := {
  FnMutInst :=
    parse_flags.closure.Insts.CoreOpsFunctionFnMutTuplePairBoolPairBoolBoolFlags
  call :=
    parse_flags.closure.Insts.CoreOpsFunctionFnTuplePairBoolPairBoolBoolFlags.call
}

/-- [rusthammer::parse_flags]:
    Source: 'src/lib.rs', lines 1108:0-1124:1
    Visibility: public -/
def parse_flags
  (input : Slice Std.U8) (cursor : Cursor) :
  Result (core.result.Result (Cursor × Flags) ParseError)
  := do
  Parser.parse.default (Map.Insts.RusthammerParser
    (Seq.Insts.RusthammerParserInputPair Bit.Insts.RusthammerParserInputBool
    (Seq.Insts.RusthammerParserInputPair Bit.Insts.RusthammerParserInputBool
    Bit.Insts.RusthammerParserInputBool))
    parse_flags.closure.Insts.CoreOpsFunctionFnTuplePairBoolPairBoolBoolFlags)
    {
      parser := { first := (), second := { first := (), second := () } },
      map := ()
    } input cursor

/-- [rusthammer::Marker]
    Source: 'src/lib.rs', lines 1151:0-1153:1
    Visibility: public -/
structure Marker where
  parser : Seq (Choice Literal Literal) End

/-- [rusthammer::{impl core::clone::Clone for rusthammer::Marker}::clone]:
    Source: 'src/lib.rs', lines 1150:9-1150:14
    Visibility: public -/
def Marker.Insts.CoreCloneClone.clone (self : Marker) : Result Marker := do
  ok self

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::Marker}]
    Source: 'src/lib.rs', lines 1150:9-1150:14 -/
@[reducible]
def Marker.Insts.CoreCloneClone : core.clone.Clone Marker := {
  clone := Marker.Insts.CoreCloneClone.clone
}

/-- [rusthammer::{rusthammer::Marker}::new]:
    Source: 'src/lib.rs', lines 1158:4-1173:5
    Visibility: public -/
def Marker.new : Result (core.result.Result Marker ConfigError) := do
  let r ← Literal.new 16#u8 51966#u64
  match r with
  | core.result.Result.Ok parser =>
    let r1 ← Literal.new 8#u8 202#u64
    match r1 with
    | core.result.Result.Ok parser1 =>
      ok (core.result.Result.Ok
        {
          parser :=
            { first := { first := parser, second := parser1 }, second := () }
        })
    | core.result.Result.Err error => ok (core.result.Result.Err error)
  | core.result.Result.Err error => ok (core.result.Result.Err error)

/-- [rusthammer::{impl rusthammer::Parser<'input, u64> for rusthammer::Marker}::parse_with]:
    Source: 'src/lib.rs', lines 1179:4-1190:5
    Visibility: public -/
def Marker.Insts.RusthammerParserInputU64.parse_with
  (self : Marker) (input : Slice Std.U8) (cursor : Cursor)
  (status : InputStatus) :
  Result (ParseOutcome Std.U64)
  := do
  let po ←
    Seq.Insts.RusthammerParserInputPair.parse_with
      (Choice.Insts.RusthammerParser Literal.Insts.RusthammerParserInputU64
      Literal.Insts.RusthammerParserInputU64)
      End.Insts.RusthammerParserInputTuple self.parser input cursor status
  match po with
  | ParseOutcome.Success next p =>
    let (value, _) := p
    ok (ParseOutcome.Success next value)
  | ParseOutcome.Error error => ok (ParseOutcome.Error error)
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, u64> for rusthammer::Marker}]
    Source: 'src/lib.rs', lines 1176:0-1191:1 -/
@[reducible]
impl_def Marker.Insts.RusthammerParserInputU64 : Parser Marker Std.U64 := {
  parse_with := Marker.Insts.RusthammerParserInputU64.parse_with
  parse := Parser.parse.default Marker.Insts.RusthammerParserInputU64
}

/-- [rusthammer::parse_marker]:
    Source: 'src/lib.rs', lines 1194:0-1200:1
    Visibility: public -/
def parse_marker
  (input : Slice Std.U8) (cursor : Cursor) (parser : Marker) :
  Result (core.result.Result (Cursor × Std.U64) ParseError)
  := do
  Parser.parse.default Marker.Insts.RusthammerParserInputU64 parser input
    cursor

/-- [rusthammer::MAX_RECORD_PAYLOAD]
    Source: 'src/lib.rs', lines 1203:0-1203:41
    Visibility: public -/
@[global_simps, irreducible] def MAX_RECORD_PAYLOAD : Std.U64 := 1024#u64

/-- [rusthammer::Record]
    Source: 'src/lib.rs', lines 1207:0-1211:1
    Visibility: public -/
structure Record where
  version : Std.U64
  flags : Std.U64
  payload : Slice Std.U8

/-- [rusthammer::RecordParser]
    Source: 'src/lib.rs', lines 1222:0-1226:1
    Visibility: public -/
structure RecordParser where
  version : Bits
  flags : Bits
  length : Bits

/-- [rusthammer::{impl core::clone::Clone for rusthammer::RecordParser}::clone]:
    Source: 'src/lib.rs', lines 1221:9-1221:14
    Visibility: public -/
def RecordParser.Insts.CoreCloneClone.clone
  (self : RecordParser) : Result RecordParser := do
  ok self

/-- Trait implementation: [rusthammer::{impl core::clone::Clone for rusthammer::RecordParser}]
    Source: 'src/lib.rs', lines 1221:9-1221:14 -/
@[reducible]
def RecordParser.Insts.CoreCloneClone : core.clone.Clone RecordParser := {
  clone := RecordParser.Insts.CoreCloneClone.clone
}

/-- [rusthammer::{rusthammer::RecordParser}::new]:
    Source: 'src/lib.rs', lines 1230:4-1248:5
    Visibility: public -/
def RecordParser.new
  : Result (core.result.Result RecordParser ConfigError) := do
  let r ← Bits.new 3#u8
  match r with
  | core.result.Result.Ok parser =>
    let r1 ← Bits.new 5#u8
    match r1 with
    | core.result.Result.Ok parser1 =>
      let r2 ← Bits.new 16#u8
      match r2 with
      | core.result.Result.Ok parser2 =>
        ok (core.result.Result.Ok
          { version := parser, flags := parser1, length := parser2 })
      | core.result.Result.Err error => ok (core.result.Result.Err error)
    | core.result.Result.Err error => ok (core.result.Result.Err error)
  | core.result.Result.Err error => ok (core.result.Result.Err error)

/-- [rusthammer::parse_record_body]:
    Source: 'src/lib.rs', lines 1289:0-1313:1 -/
def parse_record_body
  (input : Slice Std.U8) (cursor : Cursor) (version : Std.U64)
  (flags : Std.U64) (count : Std.Usize) (status : InputStatus) :
  Result (ParseOutcome Record)
  := do
  let po ←
    Seq.Insts.RusthammerParserInputPair.parse_with
      TakeAligned.Insts.RusthammerParserInputSharedInputSliceU8
      End.Insts.RusthammerParserInputTuple { first := { count }, second := () }
      input cursor status
  match po with
  | ParseOutcome.Success «end» p =>
    let (payload, _) := p
    ok (ParseOutcome.Success «end» { version, flags, payload })
  | ParseOutcome.Error error => ok (ParseOutcome.Error error)
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- [rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with::{closure}]
    Source: 'src/lib.rs', lines 1274:23-1276:13 -/
@[reducible]
def ParserInputRecordParserRecord.parse_with.closure := Unit

/-- [rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with::{impl core::ops::function::Fn<(&'_1 (u64, (u64, u64)),), bool> for rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with::{closure}<'input>}::call]:
    Source: 'src/lib.rs', lines 1274:23-1276:13 -/
def
  ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnTupleShared0PairU64PairU64U64Bool.call
  (c : ParserInputRecordParserRecord.parse_with.closure)
  (tupled_args : (Std.U64 × (Std.U64 × Std.U64))) :
  Result Bool
  := do
  let (i, p) := tupled_args
  if i = 1#u64
  then let (_, i1) := p
       ok (i1 <= MAX_RECORD_PAYLOAD)
  else ok false

/-- [rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with::{impl core::ops::function::FnMut<(&'_1 (u64, (u64, u64)),), bool> for rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with::{closure}<'input>}::call_mut]:
    Source: 'src/lib.rs', lines 1274:23-1276:13 -/
def
  ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnMutTupleShared0PairU64PairU64U64Bool.call_mut
  (state : ParserInputRecordParserRecord.parse_with.closure)
  (args : (Std.U64 × (Std.U64 × Std.U64))) :
  Result (Bool × ParserInputRecordParserRecord.parse_with.closure)
  := do
  let b ←
    ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnTupleShared0PairU64PairU64U64Bool.call
      () args
  ok (b, ())

/-- [rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with::{impl core::ops::function::FnOnce<(&'_1 (u64, (u64, u64)),), bool> for rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with::{closure}<'input>}::call_once]:
    Source: 'src/lib.rs', lines 1274:23-1276:13 -/
def
  ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnOnceTupleShared0PairU64PairU64U64Bool.call_once
  (c : ParserInputRecordParserRecord.parse_with.closure)
  (p : (Std.U64 × (Std.U64 × Std.U64))) :
  Result Bool
  := do
  let (b, _) ←
    ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnMutTupleShared0PairU64PairU64U64Bool.call_mut
      () p
  ok b

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with::{impl core::ops::function::FnOnce<(&'_1 (u64, (u64, u64)),), bool> for rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with::{closure}<'input>}]
    Source: 'src/lib.rs', lines 1274:23-1276:13 -/
@[reducible]
def
  ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnOnceTupleShared0PairU64PairU64U64Bool
  : core.ops.function.FnOnce ParserInputRecordParserRecord.parse_with.closure
  (Std.U64 × (Std.U64 × Std.U64)) Bool := {
  call_once :=
    ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnOnceTupleShared0PairU64PairU64U64Bool.call_once
}

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with::{impl core::ops::function::FnMut<(&'_1 (u64, (u64, u64)),), bool> for rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with::{closure}<'input>}]
    Source: 'src/lib.rs', lines 1274:23-1276:13 -/
@[reducible]
def
  ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnMutTupleShared0PairU64PairU64U64Bool
  : core.ops.function.FnMut ParserInputRecordParserRecord.parse_with.closure
  (Std.U64 × (Std.U64 × Std.U64)) Bool := {
  FnOnceInst :=
    ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnOnceTupleShared0PairU64PairU64U64Bool
  call_mut :=
    ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnMutTupleShared0PairU64PairU64U64Bool.call_mut
}

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with::{impl core::ops::function::Fn<(&'_1 (u64, (u64, u64)),), bool> for rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with::{closure}<'input>}]
    Source: 'src/lib.rs', lines 1274:23-1276:13 -/
@[reducible]
def
  ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnTupleShared0PairU64PairU64U64Bool
  : core.ops.function.Fn ParserInputRecordParserRecord.parse_with.closure
  (Std.U64 × (Std.U64 × Std.U64)) Bool := {
  FnMutInst :=
    ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnMutTupleShared0PairU64PairU64U64Bool
  call :=
    ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnTupleShared0PairU64PairU64U64Bool.call
}

/-- [rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}::parse_with]:
    Source: 'src/lib.rs', lines 1254:4-1286:5
    Visibility: public -/
def RecordParser.Insts.RusthammerParserInputRecord.parse_with
  (self : RecordParser) (input : Slice Std.U8) (cursor : Cursor)
  (status : InputStatus) :
  Result (ParseOutcome Record)
  := do
  let po ←
    TakeAligned.Insts.RusthammerParserInputSharedInputSliceU8.parse_with
      { count := 0#usize } input cursor status
  match po with
  | ParseOutcome.Success _ _ =>
    let po1 ←
      Verify.Insts.RusthammerParser.parse_with
        (Seq.Insts.RusthammerParserInputPair
        Bits.Insts.RusthammerParserInputU64
        (Seq.Insts.RusthammerParserInputPair
        Bits.Insts.RusthammerParserInputU64
        Bits.Insts.RusthammerParserInputU64))
        ParserInputRecordParserRecord.parse_with.closure.Insts.CoreOpsFunctionFnTupleShared0PairU64PairU64U64Bool
        {
          parser :=
            {
              first := self.version,
              second := { first := self.flags, second := self.length }
            },
          predicate := ()
        } input cursor status
    match po1 with
    | ParseOutcome.Success next p =>
      let (version, (flags, length)) := p
      let i ← lift (UScalar.cast .Usize length)
      parse_record_body input next version flags i status
    | ParseOutcome.Error error => ok (ParseOutcome.Error error)
    | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore
  | ParseOutcome.Error error => ok (ParseOutcome.Error error)
  | ParseOutcome.NeedMore => ok ParseOutcome.NeedMore

/-- Trait implementation: [rusthammer::{impl rusthammer::Parser<'input, rusthammer::Record<'input>> for rusthammer::RecordParser}]
    Source: 'src/lib.rs', lines 1251:0-1287:1 -/
@[reducible]
impl_def RecordParser.Insts.RusthammerParserInputRecord : Parser RecordParser
  Record := {
  parse_with := RecordParser.Insts.RusthammerParserInputRecord.parse_with
  parse := Parser.parse.default RecordParser.Insts.RusthammerParserInputRecord
}

/-- [rusthammer::parse_record]:
    Source: 'src/lib.rs', lines 1316:0-1322:1
    Visibility: public -/
def parse_record
  (input : Slice Std.U8) (cursor : Cursor) (parser : RecordParser) :
  Result (core.result.Result (Cursor × Record) ParseError)
  := do
  Parser.parse.default RecordParser.Insts.RusthammerParserInputRecord parser
    input cursor

end RustHammer.Code
